### ISSUE TITLE
Failure in running 'orbs sitelle  laser.job start --laser'

### ISSUE THREAD

**Issue by darioflute** [thomasorb/orbs#10]
Hi,
I was interested in reducing some SITELLE data. So I installed successfully all the packages you created (ORB, ORBS, and ORC) and I tried to compute a comparison. 
After figuring out that the 'orbs' script is in the orbs/scripts directory, I created a laser.job input file and tried to run the command:
orbs sitelle laser.job start --laser

It seemed to run well at the beginning, but then it stopped with a series of errors.
This is the log:
[laser2.job.log](https://github.com/thomasorb/orbs/files/9036088/laser2.job.log)
 
And this is the output with errors:
unknown|INFO| Init of the parallel processing server with 8 threads
unknown|INFO| loading quad 1/9
unknown|INFO| processing quad 1/9
 [          ] [0%] [quad 1/9, column : 0] [remains: unknown]<function _find_max_in_column at 0x7fde24b3e050>: Traceback (most recent call last):
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/utils/parallel.py", line 35, in run_dill_encoded
    return fun(*args)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orbs-master.12f7-py3.7.egg/orbs/process.py", line 674, in _find_max_in_column
    poly_order=0, signal_range=signal_range_cm1)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fft.py", line 975, in fit
    lines, fmodel=fmodel, nofilter=nofilter, **kwargs)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fft.py", line 824, in prepare_fit
    **kwargs)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fit.py", line 2662, in _prepare_input_params
    kwargs = ip.add_lines_model(lines, **kwargs)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fit.py", line 2179, in add_lines_model
    sigma_cov_vel = self._get_sigma_cov_vel(fwhm_guess_cm1, lines_cm1)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fit.py", line 2153, in _get_sigma_cov_vel
    fwhm_guess_cm1.mean) / self.axis_step,
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/utils/fft.py", line 262, in apod2sigma
    return broadening * fwhm
TypeError: unsupported operand type(s) for *: 'float' and 'builtin_function_or_method'

Traceback (most recent call last):
  File "/home/dario/Python/orb-stable/orbs/scripts/orbs", line 249, in start
    flux_calibration=not args.noflux)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orbs-master.12f7-py3.7.egg/orbs/orbs.py", line 933, in start_reduction
    f(*args, **kwargs_dict)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orbs-master.12f7-py3.7.egg/orbs/orbs.py", line 1356, in compute_calibration_laser_map
    get_calibration_laser_spectrum=get_calibration_laser_spectrum)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orbs-master.12f7-py3.7.egg/orbs/process.py", line 754, in create_calibration_laser_map
    fitparams[x_min + ii + ijob, y_min:y_max,:]) = job()
TypeError: cannot unpack non-iterable NoneType object
<function _find_max_in_column at 0x7fde24b3bf80>: Traceback (most recent call last):
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/utils/parallel.py", line 35, in run_dill_encoded
    return fun(*args)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orbs-master.12f7-py3.7.egg/orbs/process.py", line 674, in _find_max_in_column
    poly_order=0, signal_range=signal_range_cm1)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fft.py", line 975, in fit
    lines, fmodel=fmodel, nofilter=nofilter, **kwargs)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fft.py", line 824, in prepare_fit
    **kwargs)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fit.py", line 2662, in _prepare_input_params
    kwargs = ip.add_lines_model(lines, **kwargs)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fit.py", line 2179, in add_lines_model
    sigma_cov_vel = self._get_sigma_cov_vel(fwhm_guess_cm1, lines_cm1)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fit.py", line 2153, in _get_sigma_cov_vel
    fwhm_guess_cm1.mean) / self.axis_step,
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/utils/fft.py", line 262, in apod2sigma
    return broadening * fwhm
TypeError: unsupported operand type(s) for *: 'float' and 'builtin_function_or_method'

<function _find_max_in_column at 0x7fde24b3bf80>: Traceback (most recent call last):
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/utils/parallel.py", line 35, in run_dill_encoded
    return fun(*args)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orbs-master.12f7-py3.7.egg/orbs/process.py", line 674, in _find_max_in_column
    poly_order=0, signal_range=signal_range_cm1)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fft.py", line 975, in fit
    lines, fmodel=fmodel, nofilter=nofilter, **kwargs)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fft.py", line 824, in prepare_fit
    **kwargs)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fit.py", line 2662, in _prepare_input_params
    kwargs = ip.add_lines_model(lines, **kwargs)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fit.py", line 2179, in add_lines_model
    sigma_cov_vel = self._get_sigma_cov_vel(fwhm_guess_cm1, lines_cm1)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fit.py", line 2153, in _get_sigma_cov_vel
    fwhm_guess_cm1.mean) / self.axis_step,
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/utils/fft.py", line 262, in apod2sigma
    return broadening * fwhm
TypeError: unsupported operand type(s) for *: 'float' and 'builtin_function_or_method'

<function _find_max_in_column at 0x7fde24b3bf80>: Traceback (most recent call last):
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/utils/parallel.py", line 35, in run_dill_encoded
    return fun(*args)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orbs-master.12f7-py3.7.egg/orbs/process.py", line 674, in _find_max_in_column
    poly_order=0, signal_range=signal_range_cm1)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fft.py", line 975, in fit
    lines, fmodel=fmodel, nofilter=nofilter, **kwargs)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fft.py", line 824, in prepare_fit
    **kwargs)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fit.py", line 2662, in _prepare_input_params
    kwargs = ip.add_lines_model(lines, **kwargs)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fit.py", line 2179, in add_lines_model
    sigma_cov_vel = self._get_sigma_cov_vel(fwhm_guess_cm1, lines_cm1)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fit.py", line 2153, in _get_sigma_cov_vel
    fwhm_guess_cm1.mean) / self.axis_step,
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/utils/fft.py", line 262, in apod2sigma
    return broadening * fwhm
TypeError: unsupported operand type(s) for *: 'float' and 'builtin_function_or_method'

<function _find_max_in_column at 0x7fde24b3bf80>: Traceback (most recent call last):
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/utils/parallel.py", line 35, in run_dill_encoded
    return fun(*args)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orbs-master.12f7-py3.7.egg/orbs/process.py", line 674, in _find_max_in_column
    poly_order=0, signal_range=signal_range_cm1)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fft.py", line 975, in fit
    lines, fmodel=fmodel, nofilter=nofilter, **kwargs)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fft.py", line 824, in prepare_fit
    **kwargs)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fit.py", line 2662, in _prepare_input_params
    kwargs = ip.add_lines_model(lines, **kwargs)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fit.py", line 2179, in add_lines_model
    sigma_cov_vel = self._get_sigma_cov_vel(fwhm_guess_cm1, lines_cm1)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fit.py", line 2153, in _get_sigma_cov_vel
    fwhm_guess_cm1.mean) / self.axis_step,
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/utils/fft.py", line 262, in apod2sigma
    return broadening * fwhm
TypeError: unsupported operand type(s) for *: 'float' and 'builtin_function_or_method'

<function _find_max_in_column at 0x7fde24b3e050>: Traceback (most recent call last):
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/utils/parallel.py", line 35, in run_dill_encoded
    return fun(*args)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orbs-master.12f7-py3.7.egg/orbs/process.py", line 674, in _find_max_in_column
    poly_order=0, signal_range=signal_range_cm1)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fft.py", line 975, in fit
    lines, fmodel=fmodel, nofilter=nofilter, **kwargs)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fft.py", line 824, in prepare_fit
    **kwargs)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fit.py", line 2662, in _prepare_input_params
    kwargs = ip.add_lines_model(lines, **kwargs)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fit.py", line 2179, in add_lines_model
    sigma_cov_vel = self._get_sigma_cov_vel(fwhm_guess_cm1, lines_cm1)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fit.py", line 2153, in _get_sigma_cov_vel
    fwhm_guess_cm1.mean) / self.axis_step,
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/utils/fft.py", line 262, in apod2sigma
    return broadening * fwhm
TypeError: unsupported operand type(s) for *: 'float' and 'builtin_function_or_method'

<function _find_max_in_column at 0x7fde24b3bf80>: Traceback (most recent call last):
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/utils/parallel.py", line 35, in run_dill_encoded
    return fun(*args)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orbs-master.12f7-py3.7.egg/orbs/process.py", line 674, in _find_max_in_column
    poly_order=0, signal_range=signal_range_cm1)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fft.py", line 975, in fit
    lines, fmodel=fmodel, nofilter=nofilter, **kwargs)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fft.py", line 824, in prepare_fit
    **kwargs)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fit.py", line 2662, in _prepare_input_params
    kwargs = ip.add_lines_model(lines, **kwargs)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fit.py", line 2179, in add_lines_model
    sigma_cov_vel = self._get_sigma_cov_vel(fwhm_guess_cm1, lines_cm1)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fit.py", line 2153, in _get_sigma_cov_vel
    fwhm_guess_cm1.mean) / self.axis_step,
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/utils/fft.py", line 262, in apod2sigma
    return broadening * fwhm
TypeError: unsupported operand type(s) for *: 'float' and 'builtin_function_or_method'

<function _find_max_in_column at 0x7fde24b3bf80>: Traceback (most recent call last):
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/utils/parallel.py", line 35, in run_dill_encoded
    return fun(*args)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orbs-master.12f7-py3.7.egg/orbs/process.py", line 674, in _find_max_in_column
    poly_order=0, signal_range=signal_range_cm1)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fft.py", line 975, in fit
    lines, fmodel=fmodel, nofilter=nofilter, **kwargs)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fft.py", line 824, in prepare_fit
    **kwargs)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fit.py", line 2662, in _prepare_input_params
    kwargs = ip.add_lines_model(lines, **kwargs)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fit.py", line 2179, in add_lines_model
    sigma_cov_vel = self._get_sigma_cov_vel(fwhm_guess_cm1, lines_cm1)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fit.py", line 2153, in _get_sigma_cov_vel
    fwhm_guess_cm1.mean) / self.axis_step,
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/utils/fft.py", line 262, in apod2sigma
    return broadening * fwhm
TypeError: unsupported operand type(s) for *: 'float' and 'builtin_function_or_method'

Please, let me know if you have a clue of what I am doing wrong.
Thanks,
Dario

**Comment by darioflute** [comment]
It seems that the problem was in:
anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fit.py
line 2153.
I changed to fwhm_guess_cm1.mean to fwhm_guess_cm1.mean()
to obtain a number. So, the problem in the apod2sigma of multiplying a 'float' and a 'builtin_function_or_method'.

Nevertheless, I have now a lot of WARNING, which I doubt are normal.
Any advice is welcome:

WARNING:root:Exception occured during fit: ratio must be strictly between 0 and 1
Traceback (most recent call last):
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fft.py", line 885, in prepared_fit
    **kwargs)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fit.py", line 2596, in _fit_lines_in_spectrum
    vector_err=vector_err)
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fit.py", line 162, in __init__
    self.models.append(models[i][0](params[i]))
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fit.py", line 733, in __init__
    self.check_input()
  File "/home/dario/anaconda3/envs/orb3/lib/python3.7/site-packages/orb_kernel-3.0-py3.7-linux-x86_64.egg/orb/fit.py", line 1486, in check_input
    raise ValueError('ratio must be strictly between 0 and 1')
ValueError: ratio must be strictly between 0 and 1
